---
title: "R Notebook"
output: html_notebook
---

library(cmna)
library(Deriv)

```{r}
#No 1a
f <- function(x){
  sqrt(x)-cos(x)
}
bisection(f, 0, 1, tol = 0.001, m= 10)
curve(f, xlim=c(0,3), col='blue', lwd=1, lty=2)
abline(h=0)
abline(v=0)
```

```{r}
#No 1b
f2 <- function(x){
  3*(x+1)*(x-1/2)*(x-1)
}
bisection(f2, -2, 1.5, tol = 0.001, m= 12)
curve(f2, xlim=c(0,3), col='blue', lwd=1, lty=2)

bisection(f2, -1.25, 2.5, tol = 0.001, m= 12)
curve(f2, xlim=c(0,3), col='blue', lwd=1, lty=2)
```

```{r}
#No 1c
f3 <- function(x){
  x^3 - 2*x^2 + 14*x - 6
}
bisection(f3, 0, 1, tol = 0.01, m= 7)
curve(f3, xlim=c(0,3), col='blue', lwd=1, lty=2)

bisection(f3, 1, 3.2, tol = 0.01, m= 8)
curve(f3, xlim=c(0,3), col='blue', lwd=1, lty=2)

bisection(f3, 3.2, 2.4, tol = 0.01, m= 7)
curve(f3, xlim=c(0,3), col='blue', lwd=1, lty=2)
```

```{r}
#No 2a
f4 <- function(x){
  x^2 - 6 
}
fp1 <- Deriv(f4)
newton(f4, fp1, 1, tol = 0.001, m = 5)
curve(f4, xlim=c(0,3), col='blue', lwd=1, lty=2)
```

```{r}
#No 2b
f5 <- function(x){
  x^3 - 2*x^2 + 14*x - 6
}
fp2 <- Deriv(f5)
newton(f5, fp2, 1.5, tol = 0.001, m = 3)
curve(f5, xlim=c(0,3), col='blue', lwd=1, lty=2)
```

